"""
Portfolio Website Configuration
/backend/config.py
"""

import os


class Config:
    CONTACT_NAME_MAX_LENGTH = 100
    CONTACT_SUBJECT_MAX_LENGTH = 200
    CONTACT_BODY_MAX_LENGTH = 2000
    CONTACT_EMAIL_MAX_LENGTH = 254
    CONTACT_PHONE_MAX_LENGTH = 20
    CONTACT_LINKEDIN_MAX_LENGTH = 500
    CONTACT_DEFAULT_LIST_LIMIT = 10
    CONTACT_RATE_LIMIT = "10/minute, 50/hour"

    BLOG_TITLE_MAX_LENGTH = 200
    BLOG_SLUG_MAX_LENGTH = 250
    BLOG_EXCERPT_MAX_LENGTH = 500
    BLOG_AUTHOR_MAX_LENGTH = 100
    BLOG_TAG_MAX_LENGTH = 50
    BLOG_META_DESCRIPTION_MAX_LENGTH = 160
    BLOG_SLUG_MIN_LENGTH = 3
    BLOG_DEFAULT_LIST_LIMIT = 10
    BLOG_RATE_LIMIT = "30/minute, 200/hour"
    BLOG_WRITE_RATE_LIMIT = "5/minute, 20/hour"

    # Project Domain Constants
    PROJECT_TITLE_MAX_LENGTH = 200
    PROJECT_DESCRIPTION_MAX_LENGTH = 1000
    PROJECT_GITHUB_REPO_MAX_LENGTH = 100
    PROJECT_GITHUB_OWNER_MAX_LENGTH = 100
    PROJECT_TECH_STACK_ITEM_MAX_LENGTH = 50
    PROJECT_TYPE_MAX_LENGTH = 50
    PROJECT_DEFAULT_LIST_LIMIT = 12
    PROJECT_RATE_LIMIT = "30/minute, 300/hour"
    PROJECT_WEBHOOK_RATE_LIMIT = "100/minute"

    # GitHub Integration
    GITHUB_WEBHOOK_SECRET = os.getenv('GITHUB_WEBHOOK_SECRET')
    GITHUB_ACCESS_TOKEN = os.getenv('GITHUB_ACCESS_TOKEN')

    PORTFOLIO_EMAIL = os.getenv('PORTFOLIO_EMAIL')
    RESEND_API_KEY = os.getenv('RESEND_API_KEY')

    MONGO_URI = os.getenv('MONGO_URI')

    REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
    CACHE_ENABLED = os.getenv('CACHE_ENABLED', 'True').lower() == 'true'
    CACHE_DEFAULT_TTL = 300
    CACHE_BLOG_TTL = 600
    CACHE_BLOG_SEARCH_TTL = 300
    CACHE_CONTACT_TTL = 60
    CACHE_ADMIN_TTL = 300
    CACHE_TAG_TTL = 86400
    CACHE_KEY_VERSION = 'v1'

    REDIS_MAX_CONNECTIONS = 50
    REDIS_SOCKET_CONNECT_TIMEOUT = 2
    REDIS_SOCKET_TIMEOUT = 2
    REDIS_RETRY_ON_TIMEOUT = True
    REDIS_HEALTH_CHECK_INTERVAL = 30

    RATELIMIT_STORAGE_URI = os.getenv('RATELIMIT_STORAGE_URI', REDIS_URL)
    RATELIMIT_STRATEGY = "moving-window"
    RATELIMIT_HEADERS_ENABLED = True
    RATELIMIT_SWALLOW_ERRORS = True
    FLASK_LIMITER_BURST = "50/second"

    SECRET_KEY = os.getenv('SECRET_KEY')
    DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'


class DevelopmentConfig(Config):
    DEBUG = True


class ProductionConfig(Config):
    DEBUG = False


config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'default': DevelopmentConfig
}
