"""
Portfolio Website Configuration
/backend/config.py
"""

import os


class Config:
    CONTACT_NAME_MAX_LENGTH = 100
    CONTACT_SUBJECT_MAX_LENGTH = 200
    CONTACT_BODY_MAX_LENGTH = 2000
    CONTACT_EMAIL_MAX_LENGTH = 254
    CONTACT_PHONE_MAX_LENGTH = 20
    CONTACT_LINKEDIN_MAX_LENGTH = 500
    CONTACT_DEFAULT_LIST_LIMIT = 10
    CONTACT_RATE_LIMIT = "10/minute, 50/hour"

    BLOG_TITLE_MAX_LENGTH = 200
    BLOG_SLUG_MAX_LENGTH = 250
    BLOG_EXCERPT_MAX_LENGTH = 500
    BLOG_AUTHOR_MAX_LENGTH = 100
    BLOG_TAG_MAX_LENGTH = 50
    BLOG_META_DESCRIPTION_MAX_LENGTH = 160
    BLOG_SLUG_MIN_LENGTH = 3
    BLOG_DEFAULT_LIST_LIMIT = 10
    BLOG_RATE_LIMIT = "30/minute, 200/hour"
    BLOG_WRITE_RATE_LIMIT = "5/minute, 20/hour"

    PROJECT_TITLE_MAX_LENGTH = 200
    PROJECT_DESCRIPTION_MAX_LENGTH = 1000
    PROJECT_GITHUB_REPO_MAX_LENGTH = 100
    PROJECT_GITHUB_OWNER_MAX_LENGTH = 100
    PROJECT_TECH_STACK_ITEM_MAX_LENGTH = 50
    PROJECT_TYPE_MAX_LENGTH = 50
    PROJECT_DEFAULT_LIST_LIMIT = 12
    PROJECT_RATE_LIMIT = "30/minute, 300/hour"
    PROJECT_WEBHOOK_RATE_LIMIT = "100/minute"

    GH_WEBHOOK_SECRET = os.getenv('GH_WEBHOOK_SECRET')
    GH_ACCESS_TOKEN = os.getenv('GH_ACCESS_TOKEN')

    PORTFOLIO_EMAIL = os.getenv('PORTFOLIO_EMAIL')
    RESEND_API_KEY = os.getenv('RESEND_API_KEY')

    MONGO_URI = os.getenv('MONGO_URI')

    REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
    REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
    CACHE_ENABLED = os.getenv('CACHE_ENABLED', 'True').lower() == 'true'
    CACHE_DEFAULT_TTL = 300
    CACHE_BLOG_TTL = 600
    CACHE_BLOG_SEARCH_TTL = 300
    CACHE_CONTACT_TTL = 60
    CACHE_ADMIN_TTL = 300
    CACHE_TAG_TTL = 86400
    CACHE_KEY_VERSION = 'v1'

    REDIS_MAX_CONNECTIONS = 50
    REDIS_SOCKET_CONNECT_TIMEOUT = 2
    REDIS_SOCKET_TIMEOUT = 2
    REDIS_RETRY_ON_TIMEOUT = True
    REDIS_HEALTH_CHECK_INTERVAL = 30

    RATELIMIT_STORAGE_URI = os.getenv('RATELIMIT_STORAGE_URI', REDIS_URL)
    RATELIMIT_STRATEGY = "moving-window"
    RATELIMIT_HEADERS_ENABLED = True
    RATELIMIT_SWALLOW_ERRORS = True
    FLASK_LIMITER_BURST = "50/second"
    FLASK_LIMITER_PUBLIC = "1000/minute, 50000/hour"

    SECRET_KEY = os.getenv('SECRET_KEY')
    DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

    JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
    JWT_ACCESS_TOKEN_EXPIRES = 86400
    JWT_REFRESH_TOKEN_EXPIRES = 2592000
    JWT_BLACKLIST_TOKEN_EXPIRES = 86400
    JWT_ALGORITHM = 'HS256'

    ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')
    ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD')
    ADMIN_NAME_MAX_LENGTH = 100
    ADMIN_PASSWORD_MIN_LENGTH = 8
    ADMIN_MAX_FAILED_LOGIN_ATTEMPTS = 5
    ADMIN_LOCKOUT_DURATION_MINUTES = 30
    ADMIN_AUTH_RATE_LIMIT = "10/minute, 50/hour"

    GH_CLIENT_ID = os.getenv('GH_CLIENT_ID')
    GH_CLIENT_SECRET = os.getenv('GH_CLIENT_SECRET')
    BACKEND_URL = os.getenv('BACKEND_URL')
    FRONTEND_URL = os.getenv('FRONTEND_URL')

    GITHUB_ADMIN_CALLBACK_URL = f"{os.getenv('BACKEND_URL')}/api/v1/admin/auth/github/callback" if os.getenv('BACKEND_URL') else None


class DevelopmentConfig(Config):
    DEBUG = True


class ProductionConfig(Config):
    DEBUG = False


config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'default': DevelopmentConfig
}
