FROM python:3.11.3

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    build-essential \
    libffi-dev \
    gcc \
    curl \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
  
RUN python3 -m venv /venv
ENV VIRTUAL_ENV="/venv"
ENV PATH="/venv/bin:$PATH"
ENV FLASK_APP=Run.py
ENV PYTHONDONTWRITEBYTECODE=1 
ENV PYTHONUNBUFFERED=1 

COPY pyproject.toml .

RUN /venv/bin/pip install --upgrade pip setuptools wheel
RUN /venv/bin/pip install -e ".[dev]"
COPY . .

RUN mkdir -p /app/logs && chmod 755 /app/logs
RUN chmod +x Run.py

EXPOSE 5000

CMD ["watchmedo", "auto-restart", "--directory=.", "--pattern=*.py", "--recursive", "--", "python", "Run.py"]
